name: Python Pineline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: hello
          path: .
      
